[package]
name = "db-service"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
entity = { path = "../entity" }
sea-orm = { version = "1.1.0", features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
] }
serde = { version = "1", features = ["derive"] }
