/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/volt/Button.vue')['default']
    Divider: typeof import('./src/volt/Divider.vue')['default']
    IconMdiHttps: typeof import('~icons/mdi/https')['default']
    IconMdiPlay: typeof import('~icons/mdi/play')['default']
    SecondaryButton: typeof import('./src/volt/SecondaryButton.vue')['default']
    ToggleSwitch: typeof import('./src/volt/ToggleSwitch.vue')['default']
  }
}
