/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomBar: typeof import('./src/components/BottomBar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconFluentDismiss16Regular: typeof import('~icons/fluent/dismiss16-regular')['default']
    IconFluentMaximize16Regular: typeof import('~icons/fluent/maximize16-regular')['default']
    IconFluentMinimize16Regular: typeof import('~icons/fluent/minimize16-regular')['default']
    IconFluentSquareMultiple16Regular: typeof import('~icons/fluent/square-multiple16-regular')['default']
    IconMdiHttps: typeof import('~icons/mdi/https')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    WindowControls: typeof import('./src/components/WindowControls.vue')['default']
  }
}
